import { Inter } from "next/font/google";
import "./globals.scss";
import { Suspense } from "react";
import Loading from './components/views/loading';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <AppHeader/>
        <NavigationMenu/> */}
        <Suspense fallback={<Loading />}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}